#!/bin/bash

# Make the working directory and download the file you need
mkdir -p ~/finger-print-fix
cd ~/finger-print-fix
wget https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi9/9/aarch64/appstream/os/Packages/c/compat-openssl11-1.1.1k-5.el9_6.1.aarch64.rpm
sudo dnf install compat-openssl11-1.1.1k-5.el9_6.1.aarch64.rpm

# Enable the COPR with the right Fprintd library patched for our Thinkbook 14 ABA fingerprint elan
sudo dnf copr enable dolmushcu/libfprint-tod
sudo dnf update && sudo dnf upgrade -y
sudo dnf swap libfprint libfprint-tod
sudo dnf install libfprint-2-tod1-elan-0c4b
sudo systemctl restart fprintd
sudo systemctl status fprintd

# clean-up
rm -rf ~/finger-print-fix

#Register your fingers
fprintd-delete $USER
fprintd-enroll
fprintd-verify

#reboot the OS
sudo systemctl reboot
